controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    manipulator_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - ur_arm_shoulder_pan_joint
      - ur_arm_shoulder_lift_joint
      - ur_arm_elbow_joint
      - ur_arm_wrist_1_joint
      - ur_arm_wrist_2_joint
      - ur_arm_wrist_3_joint

manipulator_controller:
  ros__parameters:
    joints:
      - ur_arm_shoulder_pan_joint
      - ur_arm_shoulder_lift_joint
      - ur_arm_elbow_joint
      - ur_arm_wrist_1_joint
      - ur_arm_wrist_2_joint
      - ur_arm_wrist_3_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      ur_arm_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      ur_arm_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      ur_arm_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      ur_arm_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      ur_arm_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      ur_arm_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }
