# manipulator:
#   ros__parameters:
#     kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#     kinematics_solver_search_resolution: 0.005
#     kinematics_solver_timeout: 0.005
#     kinematics_solver_attempts: 3

# robot_description_kinematics:
#   ros__parameters:
#     manipulator:
#       kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#       kinematics_solver_search_resolution: 0.005
#       kinematics_solver_timeout: 0.005
#       kinematics_solver_attempts: 3

/**:
  ros__parameters:
    robot_description_kinematics:
      manipulator:
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.005
        kinematics_solver_timeout: 0.005
        kinematics_solver_attempts: 3